"""
Situation Aliases (The Bridge)
Maps DETECTED Situations -> SOLUTION Tags
This file merges the original logic with the new extended features.
"""

from decision_engine.constants import SITUATIONS
print("\n>>> DEBUG: [Import] decision_engine/situation_aliases.py loaded")
SITUATION_ALIASES = {
    # =========================================================
    # PART 1: ORIGINAL CORE ALIASES (EXPANDED & MERGED)
    # =========================================================

    # 1. CHAOS
    # Merged: Original tags + High Noise + Logistical issues + Interruptions
    SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"): {
        "NOISE_CONTROL", "DISRUPTIVE_BEHAVIOR", "RESTLESS_CLASS", "LOUD", 
        "BEHAVIORAL_ISSUES", "RULE_BREAKING", "AGGRESSION", "CLASSROOM_MANAGEMENT",
        "CHAOS", "NOISE_SPIKE", 
        # New Additions for Solution Matching:
        "HIGH_NOISE", "LOGISTICAL_CHAOS", "INTERRUPTIONS", "DISRESPECT_DEFIANCE", 
        "RESTLESSNESS", "MANAGEMENT_ISSUE"
    },

    # 2. ENGAGEMENT
    # Merged: Original tags + Sleepiness + Low Participation
    SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT"): {
        "LOW_ENGAGEMENT", "BOREDOM", "PASSIVE_LEARNING", "MONOTONY", 
        "DISENGAGED_STUDENTS", "ROUTINE_BOREDOM", "PASSIVITY", "UNRESPONSIVE_CLASS",
        # New Additions:
        "SLEEPINESS", "LOW_PARTICIPATION"
    },

    # 3. ATTENTION
    SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION"): {
        "LOW_ATTENTION", "LACK_OF_ATTENTION", "DISTRACTION", 
        "UNRESPONSIVE_CLASS", "LOW_PARTICIPATION", "INATTENTIVE", "FOCUS_ISSUE"
    },

    # 4. CONFUSION
    SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION"): {
        "CONCEPT_NOT_CLEAR", "UNCLEAR_UNDERSTANDING", "CONFUSION", 
        "TOPIC_DISCONNECT", "THEORY_OVERLOAD", "CONCEPTUAL_GAP", 
        "MISCONCEPTION_PERSISTENCE", "TOPIC_CONFUSION", "DOUBT_CLEARING",
        "STUDENTS_NOT_UNDERSTANDING", "DIFFICULT_TOPIC", "ACTIVITY_FAILURE"
    },

    # 5. MEMORY
    SITUATIONS.get("MEMORY_RETENTION_ISSUE", "MEMORY_RETENTION_ISSUE"): {
        "LOW_RETENTION", "RECALL_DIFFICULTY", "FACT_MEMORIZATION", 
        "FORGETFULNESS", "LOW_RECALL", "MEMORY_ISSUE"
    },

    # 6. WRITING
    # Merged: Original tags + Fine Motor + Dysgraphia
    SITUATIONS.get("WRITING_DIFFICULTY", "WRITING_DIFFICULTY"): {
        "RELUCTANT_TO_WRITE", "WEAK_WRITING", "WRITING_BLOCK", 
        "SLOW_WRITING", "HANDWRITING_ISSUE", "NOTE_TAKING",
        # New Additions:
        "FINE_MOTOR_ISSUES", "DYSGRAPHIA", "BAD_HANDWRITING"
    },

    # 7. READING/LANGUAGE
    # Merged: Original tags + Dyslexia + Comprehension
    SITUATIONS.get("READING_LANGUAGE_ISSUE", "READING_LANGUAGE_ISSUE"): {
        "READING_GAP", "LANGUAGE_GAP", "VOCABULARY_LAG", 
        "WEAK_LANGUAGE_SKILLS", "FLUENCY_ISSUE", "MIXED_READING_LEVELS",
        "GRAMMAR_ISSUES", "MOTHER_TONGUE_INFLUENCE", "LITERACY",
        # New Additions:
        "DYSLEXIA", "SLOW_READING", "COMPREHENSION_ISSUE"
    },

    # 8. SHYNESS
    SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE"): {
        "STUDENT_ISOLATED", "RELUCTANT_SPEAKERS", "LOW_CONFIDENCE", 
        "SPEAKING_HESITATION", "QUIET_CLASS", "STUDENT_ANXIETY", "SHY_STUDENTS"
    },

    # 9. MIXED LEVELS
    SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"): {
        "MIXED_LEARNING_LEVELS", "FAST_FINISHERS", "SLOW_LEARNERS", 
        "MIXED_CLASSROOM", "MULTI_GRADE", "DIFFERENTIATION_NEEDED"
    },

    # 10. TIME MANAGEMENT
    SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"): {
        "TIME_MANAGEMENT", "TRANSITION_DELAY", "SLOW_START", 
        "LESSON_WRAP_UP", "FAST_CONTENT_SHIFT", "SYLLABUS_COMPLETION"
    },
    
    # 11. HOMEWORK/PARENTS
    SITUATIONS.get("HOMEWORK_PARENT_ISSUE", "HOMEWORK_PARENT_ISSUE"): {
        "LACK_OF_HOME_SUPPORT", "PARENT_DISCONNECT", "HOMEWORK_ISSUE",
        "PARENT_ENGAGEMENT_GAP", "LACK_OF_SUPPORT", "INCOMPLETE_WORK"
    },
    
    # 12. MATH
    # Merged: Original tags + Geometry + Concept Confusion
    SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"): {
        "MATH_FEAR", "CALCULATION_ERROR", "CONCEPTUAL_CONFUSION", 
        "APPLICATION_ISSUES", "MATH_PHOBIA", "NUMERACY_ISSUE",
        # New Additions:
        "GEOMETRY_CONFUSION", "CONCEPT_CONFUSION"
    },
    
    # 13. RESOURCES
    SITUATIONS.get("RESOURCE_CONSTRAINT", "RESOURCE_CONSTRAINT"): {
        "NO_INTERNET", "POWER_CUT", "LACK_OF_RESOURCES", "INFRASTRUCTURE_ISSUE",
        "LARGE_CLASS_SIZE", "CROWDED_CLASSROOM"
    },

    # 14. EMOTIONAL
    SITUATIONS.get("EMOTIONAL_WELLBEING", "EMOTIONAL_WELLBEING"): {
        "STUDENT_WELLBEING", "TIRED_STUDENTS", "EMOTIONAL_DISTRESS",
        "HUNGER", "HEALTH_ISSUE", "EMOTIONAL_INSTABILITY"
    },

    # 15. DISRESPECT
    SITUATIONS.get("DISRESPECT_DEFIANCE", "DISRESPECT_DEFIANCE"): {
        "DEFIANCE", "RUDE_BEHAVIOR", "ARGUMENTATIVE", "REFUSAL_TO_WORK"
    },

    # =========================================================
    # PART 2: NEW EXTENDED ALIASES (THE UPGRADE)
    # =========================================================

    # 16. INCLUSION & SPECIAL NEEDS
    "ADHD": {"SPECIAL_NEEDS", "RESTLESSNESS", "DISTRACTIBILITY", "INCLUSIVE_EDUCATION", "LOW_ATTENTION"},
    "SLOW_LEARNER": {"ACADEMIC_STRUGGLE", "DIFFERENTIATION", "INCLUSIVE_EDUCATION", "SLOW_LEARNERS", "MIXED_LEARNING_LEVELS"},
    "SENSORY_IMPAIRMENT": {"SPECIAL_NEEDS", "ACCESSIBILITY", "INCLUSIVE_EDUCATION", "SENSORY_ISSUE"},
    "SHORT_ATTENTION_SPAN": {"LOW_ENGAGEMENT", "RESTLESSNESS", "FOCUS_ISSUE", "LOW_ATTENTION"},

    # 17. SCIENCE & RURAL CONTEXT
    "NO_LAB_EQUIPMENT": {"RURAL_SETTING", "LOW_RESOURCES", "HANDS_ON", "SCIENCE", "RESOURCE_CONSTRAINT"},
    "NO_ELECTRICITY": {"LOW_RESOURCES", "OFFLINE_LEARNING", "NO_TECH", "RESOURCE_CONSTRAINT"},
    
    # 18. TEACHER WELLBEING & ADMIN
    "TEACHER_BURNOUT": {"STRESS_MANAGEMENT", "SELF_CARE", "EMOTIONAL_WELLBEING", "PROFESSIONAL_SKILLS"},
    "ANGRY_PARENT": {"CONFLICT_RESOLUTION", "COMMUNICATION", "PROFESSIONAL_SKILLS", "PARENT_ISSUE", "HOMEWORK_PARENT_ISSUE"},
    "GRADING_OVERLOAD": {"TIME_MANAGEMENT", "ADMIN_STRESS", "PRODUCTIVITY", "ASSESSMENT"},

    # 19. FLN (FOUNDATIONAL LITERACY & NUMERACY)
    "LITERACY_START": {"LITERACY", "FLN", "FOUNDATIONAL_SKILLS", "READING_LANGUAGE_ISSUE"},
    "MATH_ANXIETY": {"NUMERACY", "FLN", "CONCEPT_CONFUSION", "MATH_DIFFICULTY"},
    
    # 20. MANAGEMENT NUANCES
    # (Note: Removed duplicate "CLASSROOM_CHAOS" key here to prevent overwriting Part 1)
    "LARGE_CLASS_SIZE": {"CROWDED_CLASSROOM", "LOGISTICAL_CHAOS", "HIGH_NOISE", "RESOURCE_CONSTRAINT"},
    # 21. REDDIT SOLUTION BRIDGES (Reverse Mapped)
    "TASK_INITIATION": {"STARTING_TROUBLE", "WRITING_BLOCK", "PROCRASTINATION", "LOW_ENGAGEMENT"},
    "SIDE_TALK": {"DISTRACTION_CLUSTER", "OFF_TASK_BEHAVIOR", "CLASSROOM_CHAOS", "NOISE_BUILDUP"},
    "QUESTION_PILEUP": {"INTERRUPTIONS", "TIME_DRAIN", "HIGH_CURIOSITY", "MANAGEMENT_ISSUE"},
    "MID_LESSON_CONFUSION": {"CONFUSION", "LOSS_OF_THREAD", "CONCEPT_DRIFT", "ATTENTION_DROP"},
    "END_OF_CLASS_DRIFT": {"TRANSITION_CONFUSION", "LOW_RETENTION", "CLOSURE_ISSUE", "TIME_MANAGEMENT"},
    "RANDOM_ATTEMPTS": {"GUESSING", "CONCEPT_CONFUSION", "LOW_CONFIDENCE", "STRATEGY_DEFICIT"},
    "INFORMATION_OVERLOAD": {"COGNITIVE_LOAD", "CONFUSION", "OVERWHELMED", "COMPLEXITY"},

    # =========================================================
    # PART 3: CRITICAL UNMAPPED DETECTION TAGS (38 tags)
    # These were previously falling through the cracks
    # =========================================================
    
    # Cognitive State Bridges
    "CONFUSION": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "BOREDOM": {SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "FATIGUE": {SITUATIONS.get("EMOTIONAL_WELLBEING", "EMOTIONAL_WELLBEING")},
    "LOW_MOTIVATION": {SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "LOW_RECALL": {SITUATIONS.get("MEMORY_RETENTION_ISSUE", "MEMORY_RETENTION_ISSUE")},
    "PROCESSING_LAG": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION"), SITUATIONS.get("MEMORY_RETENTION_ISSUE", "MEMORY_RETENTION_ISSUE")},
    "OVERSTIMULATION": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"), SITUATIONS.get("EMOTIONAL_WELLBEING", "EMOTIONAL_WELLBEING")},
    
    # Instructional Moments Bridges
    "TASK_STALL": {SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "WRITING_BLOCK": {SITUATIONS.get("WRITING_DIFFICULTY", "WRITING_DIFFICULTY"), SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "MESSY_TRANSITION": {SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "EARLY_FINISHERS": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    
    # Classroom Behavior Bridges
    "HIGH_NOISE": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "DISRESPECT_DEFIANCE": {SITUATIONS.get("DISRESPECT_DEFIANCE", "DISRESPECT_DEFIANCE"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "DISTRACTIBILITY": {SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "LOSS_OF_FOCUS": {SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION")},
    "RESTLESSNESS": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"), SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "SILENT_CLASS": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE"), SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "UNRESPONSIVE_CLASS": {SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT"), SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION")},
    "INTERRUPTIONS": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "LOGISTICAL_CHAOS": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"), SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE")},
    
    # Math Topic Bridges
    "GEOMETRY_2D_3D": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "FRACTIONS": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "RATIO_PROPORTION": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "DECIMALS": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "PLACE_VALUE": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "BASIC_ALGEBRA": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY"), SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "MATH_DIFFICULTY": {SITUATIONS.get("MATH_DIFFICULTY", "MATH_DIFFICULTY")},
    
    # Science Topic Bridges
    "PLANTS_FUNCTIONS": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "ASTRONOMY": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "HUMAN_BODY": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    
    # Language Topic Bridges
    "WRITING_DIFFICULTY": {SITUATIONS.get("WRITING_DIFFICULTY", "WRITING_DIFFICULTY")},
    "READING_LANGUAGE_ISSUE": {SITUATIONS.get("READING_LANGUAGE_ISSUE", "READING_LANGUAGE_ISSUE")},
    "GRAMMAR_ISSUES": {SITUATIONS.get("READING_LANGUAGE_ISSUE", "READING_LANGUAGE_ISSUE"), SITUATIONS.get("WRITING_DIFFICULTY", "WRITING_DIFFICULTY")},
    "FEAR_OF_SPEAKING": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE"), SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "SHYNESS": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE")},
    
    # Teacher Pain Points Bridges
    "TIME_MANAGEMENT": {SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE")},
    "LESSON_PLANNING": {SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"), SITUATIONS.get("RESOURCE_CONSTRAINT", "RESOURCE_CONSTRAINT")},
    "ADMIN_STRESS": {SITUATIONS.get("EMOTIONAL_WELLBEING", "EMOTIONAL_WELLBEING"), SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE")},

    # =========================================================
    # PART 4: REAL-WORLD PEDAGOGICAL CONTEXTS
    # For collaborative, differentiated, and confidence-building scenarios
    # =========================================================
    
    # Collaborative Learning Contexts
    "COOPERATIVE_LEARNING": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "GROUP_PROJECT": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"), SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE")},
    "TEAMWORK": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "PARTNER_WORK": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    
    # Focus & Attention in group contexts
    "FOCUS_DURING_ACTIVITY": {SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "FOCUS_IN_GROUP": {SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION"), SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    
    # Pace & Differentiation
    "PACING_ISSUE": {SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"), SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    "SPEED_DIFFERENCES": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"), SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE")},
    "WORK_COMPLETION": {SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"), SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    
    # Confidence building contexts
    "BUILD_CONFIDENCE": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE")},
    "PARTICIPATION_ISSUE": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE"), SITUATIONS.get("LOW_ENGAGEMENT", "LOW_ENGAGEMENT")},
    "SPEAKING_ANXIETY": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE")},
    "ANSWER_HESITATION": {SITUATIONS.get("SHYNESS_LOW_CONFIDENCE", "SHYNESS_LOW_CONFIDENCE")},
    
    # Explanation & teaching difficulty
    "EXPLANATION_DIFFICULTY": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "TEACH_DIFFICULT_CONCEPT": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION")},
    "STRUGGLING_STUDENT": {SITUATIONS.get("CONCEPT_CONFUSION", "CONCEPT_CONFUSION"), SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS")},
    
    # Group Project & Collaborative Learning (NEW)
    "GROUP_PROJECT": {
        SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"),
        SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"),
        SITUATIONS.get("TIME_MANAGEMENT_ISSUE", "TIME_MANAGEMENT_ISSUE"),
        "COOPERATIVE_LEARNING",
        "TEAMWORK",
        "COLLABORATION"
    },
    
    # Turn-taking & listening
    "LISTENING_SKILL": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"), SITUATIONS.get("DISRESPECT_DEFIANCE", "DISRESPECT_DEFIANCE")},
    "TURN_TAKING": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
    "INTERRUPTION_PROBLEM": {SITUATIONS.get("INTERRUPTIONS", "INTERRUPTIONS")},
    
    # Special needs in group settings
    "ADHD_IN_CLASS": {SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS"), SITUATIONS.get("LOW_ATTENTION", "LOW_ATTENTION")},
    "ADHD_GROUP_ACTIVITY": {SITUATIONS.get("MIXED_LEVELS", "MIXED_LEVELS"), SITUATIONS.get("CLASSROOM_CHAOS", "CLASSROOM_CHAOS")},
}
