"""
Situation Aliases (The Bridge)
Maps NEW Master Situations -> OLD Solution Tags
"""

from decision_engine.constants import SITUATIONS

SITUATION_ALIASES = {
    # 1. CHAOS -> Old Tags
    SITUATIONS["CLASSROOM_CHAOS"]: {
        "NOISE_CONTROL", "DISRUPTIVE_BEHAVIOR", "RESTLESS_CLASS", "LOUD", 
        "BEHAVIORAL_ISSUES", "RULE_BREAKING", "AGGRESSION", "CLASSROOM_MANAGEMENT",
        "CHAOS", "NOISE_SPIKE"
    },

    # 2. ENGAGEMENT -> Old Tags
    SITUATIONS["LOW_ENGAGEMENT"]: {
        "LOW_ENGAGEMENT", "BOREDOM", "PASSIVE_LEARNING", "MONOTONY", 
        "DISENGAGED_STUDENTS", "ROUTINE_BOREDOM", "PASSIVITY", "UNRESPONSIVE_CLASS"
    },

    # 3. ATTENTION -> Old Tags
    SITUATIONS["LOW_ATTENTION"]: {
        "LOW_ATTENTION", "LACK_OF_ATTENTION", "DISTRACTION", 
        "UNRESPONSIVE_CLASS", "LOW_PARTICIPATION", "INATTENTIVE", "FOCUS_ISSUE"
    },

    # 4. CONFUSION -> Old Tags
    SITUATIONS["CONCEPT_CONFUSION"]: {
        "CONCEPT_NOT_CLEAR", "UNCLEAR_UNDERSTANDING", "CONFUSION", 
        "TOPIC_DISCONNECT", "THEORY_OVERLOAD", "CONCEPTUAL_GAP", 
        "MISCONCEPTION_PERSISTENCE", "TOPIC_CONFUSION", "DOUBT_CLEARING",
        "STUDENTS_NOT_UNDERSTANDING", "DIFFICULT_TOPIC", "ACTIVITY_FAILURE"
    },

    # 5. MEMORY -> Old Tags
    SITUATIONS["MEMORY_RETENTION_ISSUE"]: {
        "LOW_RETENTION", "RECALL_DIFFICULTY", "FACT_MEMORIZATION", 
        "FORGETFULNESS", "LOW_RECALL", "MEMORY_ISSUE"
    },

    # 6. WRITING -> Old Tags
    SITUATIONS["WRITING_DIFFICULTY"]: {
        "RELUCTANT_TO_WRITE", "WEAK_WRITING", "WRITING_BLOCK", 
        "SLOW_WRITING", "HANDWRITING_ISSUE", "NOTE_TAKING"
    },

    # 7. READING/LANGUAGE -> Old Tags
    SITUATIONS["READING_LANGUAGE_ISSUE"]: {
        "READING_GAP", "LANGUAGE_GAP", "VOCABULARY_LAG", 
        "WEAK_LANGUAGE_SKILLS", "FLUENCY_ISSUE", "MIXED_READING_LEVELS",
        "GRAMMAR_ISSUES", "MOTHER_TONGUE_INFLUENCE"
    },

    # 8. SHYNESS -> Old Tags
    SITUATIONS["SHYNESS_LOW_CONFIDENCE"]: {
        "STUDENT_ISOLATED", "RELUCTANT_SPEAKERS", "LOW_CONFIDENCE", 
        "SPEAKING_HESITATION", "QUIET_CLASS", "STUDENT_ANXIETY", "SHY_STUDENTS"
    },

    # 9. MIXED LEVELS -> Old Tags
    SITUATIONS["MIXED_LEVELS"]: {
        "MIXED_LEARNING_LEVELS", "FAST_FINISHERS", "SLOW_LEARNERS", 
        "MIXED_CLASSROOM", "MULTI_GRADE", "DIFFERENTIATION_NEEDED"
    },

    # 10. TIME -> Old Tags
    SITUATIONS["TIME_MANAGEMENT_ISSUE"]: {
        "TIME_MANAGEMENT", "TRANSITION_DELAY", "SLOW_START", 
        "LESSON_WRAP_UP", "FAST_CONTENT_SHIFT", "SYLLABUS_COMPLETION"
    },
    
    # 11. HOMEWORK -> Old Tags
    SITUATIONS["HOMEWORK_PARENT_ISSUE"]: {
        "LACK_OF_HOME_SUPPORT", "PARENT_DISCONNECT", "HOMEWORK_ISSUE",
        "PARENT_ENGAGEMENT_GAP", "LACK_OF_SUPPORT", "INCOMPLETE_WORK"
    },
    
    # 12. MATH -> Old Tags
    SITUATIONS["MATH_DIFFICULTY"]: {
        "MATH_FEAR", "CALCULATION_ERROR", "CONCEPTUAL_CONFUSION", 
        "APPLICATION_ISSUES", "MATH_PHOBIA", "NUMERACY_ISSUE"
    },
    
    # 13. RESOURCES -> Old Tags
    SITUATIONS["RESOURCE_CONSTRAINT"]: {
        "NO_INTERNET", "POWER_CUT", "LACK_OF_RESOURCES", "INFRASTRUCTURE_ISSUE",
        "LARGE_CLASS_SIZE", "CROWDED_CLASSROOM"
    },

    # 14. EMOTIONAL -> Old Tags
    SITUATIONS["EMOTIONAL_WELLBEING"]: {
        "STUDENT_WELLBEING", "TIRED_STUDENTS", "EMOTIONAL_DISTRESS",
        "HUNGER", "HEALTH_ISSUE", "EMOTIONAL_INSTABILITY"
    },

    # 15. DISRESPECT -> Old Tags
    SITUATIONS["DISRESPECT_DEFIANCE"]: {
        "DEFIANCE", "RUDE_BEHAVIOR", "ARGUMENTATIVE", "REFUSAL_TO_WORK"
    }
}